# Level 2 
This file will consist of answer to question to 6 - ,which qualify as level 2 in difficulty or require moderate experince to understand and answer.

# Question 6

Question:
Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma-separated input sequence is given to the program:
100,150,180

The output of the program should be:
18,22,24

Hints:

If the output received is in decimal form, it should be rounded off to its nearest value (for example, if the output received is 26.0, it should be printed as 26)
In case of input data being supplied to the question, it should be assumed to be a console input. 


In [3]:
# Import Libraries

import math

# Define Given

J = 50
Y = 30
Z = []
equation = (x for x in input().split(','))

# Define D

for D in equation:
    Z.append(str(int(round(math.sqrt((2*J*float(D))//Y)))))

# Print Output

print(','.join(Z))

 100,150,180


18,22,24


# Question 7

Question:

Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡­Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 

Hints:

Note: In case of input data being supplied to the question, it should be assumed to be a console input in a comma-separated form.

In [11]:
# Import necessary libraries

import numpy as np

# Define variables

x = int(float(input("how many Rows?")))      # Rows
y = int(float(input("How many Columns?")))   # Columns
fill_value = int(input("Enter the fill value: ")) # a single integer to fill the array

# combine variables into an array

z = np.full((x,y),fill_value)

# Output

print(" ")
print(z)

how many Rows? 5
How many Columns? 5
Enter the fill value:  8


 
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


# Question 8

Question:

Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.


In [20]:
# Input for line

words = [x for x in input("input comma separated words:").split(",")]
words = sorted(words)

# Output

print(",".join(words))

input comma separated words: blue, green, crayon, apple, green


 apple, crayon, green, green,blue


# Question 9

Question:

Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.

Suppose the following input is supplied to the program:

Hello world
Practice makes perfect

Then, the output should be:

HELLO WORLD
PRACTICE MAKES PERFECT

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.


In [23]:
# Develop input system for the sequence of lines

fxck =[]
while True:
    x = input()
    if x:
        fxck.append(x.upper())
    else:
        break;

# Print output
for sentence in fxck:
    print(sentence)


 Sally sells seashells by the seashore
 seashells are free
 fuck sally
 


SALLY SELLS SEASHELLS BY THE SEASHORE
SEASHELLS ARE FREE
FUCK SALLY


# Question 10

Question:

Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world

Hints:

In case of input data being supplied to the question, it should be assumed to be a console input.
We use set container to remove duplicated data automatically and then use sorted() to sort the data.



In [32]:
# Input string of words

x = input("Input words:")

# Remove duplicate words and sort

y = [word for word in x.split(" ")]
z = sorted(list(set(y)))

# Print output

print(" ".join(z))

Input words: World Hello


Hello World


# Question 11

Question: Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence. 

Example: 0100,0011,1010,1001 

Then the output should be: 1010 

Notes: Assume the data is input by console.

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [35]:
# Input Method

X = []
Y = [x for x in input("Input binary string (use , after 4-digits):").split(',')]

# Digestion

for i in Y:
    Y = int(i,2)
    if not Y%5:
        X.append(i)
    
#Output

print(','.join(X))

Input binary string (use , after 4-digits): 0100,0011,1010,1001


1010


# Question 12

Question: Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number. The numbers obtained should be printed in a comma-separated sequence on a single line.

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [38]:
# Find even numbers between 1000 & 3000 inclusive

x = []
for i in range(1000,3001):
    y = str(i)
    if (int(y[0])%2 == 0) and (int(y[1])%2 == 0) and (int(y[2])%2 == 0) and (int(y[3])%2 == 0):
          x.append(y)

# Print

print(','.join(x))

2000,2002,2004,2006,2008,2020,2022,2024,2026,2028,2040,2042,2044,2046,2048,2060,2062,2064,2066,2068,2080,2082,2084,2086,2088,2200,2202,2204,2206,2208,2220,2222,2224,2226,2228,2240,2242,2244,2246,2248,2260,2262,2264,2266,2268,2280,2282,2284,2286,2288,2400,2402,2404,2406,2408,2420,2422,2424,2426,2428,2440,2442,2444,2446,2448,2460,2462,2464,2466,2468,2480,2482,2484,2486,2488,2600,2602,2604,2606,2608,2620,2622,2624,2626,2628,2640,2642,2644,2646,2648,2660,2662,2664,2666,2668,2680,2682,2684,2686,2688,2800,2802,2804,2806,2808,2820,2822,2824,2826,2828,2840,2842,2844,2846,2848,2860,2862,2864,2866,2868,2880,2882,2884,2886,2888


# Question 13

Question: Write a program that accepts a sentence and calculate the number of letters and digits. Suppose the following input is supplied to the program: hello world! 123 Then, the output should be: LETTERS 10 DIGITS 3

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.



In [50]:
# Input sentence

x = input("Write a sentence:")

# Calculte # of letters & digits seperately

y = {"letters":0, "digits":0}
for count in x:
    if count.isdigit():                      # .isdigit() will count the digits in a string
        y["digits"]+=1
    elif count.isalpha():                    # .isalpha() will count the letters in a string
        y["letters"]+=1
    else:
        pass

# Print Output
print(" ")
print("Letters:",y["letters"],"    ","Numbers:",y["digits"]) # recheck the code count seems to be off

Write a sentence: Hello world and Good night 2night


 
Letters: 27      Numbers: 1


# Question 14

Question: Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters. Suppose the following input is supplied to the program: Hello world! Then, the output should be: UPPER CASE 1 LOWER CASE 9

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [53]:
# Input

x = input("Write a sentence:")

# Count upper and lower case letters

str(x)
y = {"Upper case":0, "Lower case":0}
for count in x:
    if count.isupper():                      # .isupper() will count the upper case letters in a string
        y["Upper case"]+=1
    elif count.islower():                    # .islower() will count the lower case letters in a string
        y["Lower case"]+=1
    else:
        pass

# Output

print("Upper case count:",y["Upper case"])
print("Lower case count:",y["Lower case"])

Write a sentence: Goodnight world


Upper case count: 1
Lower case count: 13


# Question 15

Question: Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a. Suppose the following input is supplied to the program: 9 Then, the output should be: 11106

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [56]:
# Input Number and assign to a

n = input("insert a single-digit here (0-9):")

# Formula and expression

x1 = int(("%s" % n))
x2 = int(("%s%s" % (n,n)))
x3 = int(("%s%s%s" % (n,n,n)))
x4 = int(("%s%s%s%s" % (n,n,n,n)))
y = x1+x2+x3+x4

# Print Output
print("")
print(y)

insert a single-digit here (0-9): 8



9872


# Question 16

Question: Use a list comprehension to square each odd number in a list. The list is input by a sequence of comma-separated numbers. Suppose the following input is supplied to the program: 1,2,3,4,5,6,7,8,9 Then, the output should be: 1,3,5,7,9

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [61]:
# Input comma-seperated numbers

csn = input("Type comma-seperated numbers here:")

# seperate the Odd numbers

y = [ x for x in csn.split(",") if int(x)%2 != 0 ]

# Output

print(y)

Type comma-seperated numbers here: 1,2,3,4,5,6,7,8,9,0


['1', '3', '5', '7', '9']


# Question 17

Question: 
Write a program that computes the net amount of a bank account based a transaction log from console input. The transaction log format is shown as following: D 100 W 200

D means deposit while W means withdrawal. 

Suppose the following input is supplied to the program: D 300 D 300 W 200 D 100 
Then, the output should be: 500

Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [64]:
# Create transaction history

account_balance = 0
while True:
    x = input("Input amount you would like to withdraw/deposit (W/D $$$):")
    if not x:
        break
    value = x.split(" ")
    operation = value[0]
    amount = int(value[1])
    if operation == "D":
        account_balance +=amount
    elif operation == "W":
        account_balance -=amount
else:
    pass

# Output remaining balance

print("")
print("$",account_balance)

Input amount you would like to withdraw/deposit (W/D $$$): D 200
Input amount you would like to withdraw/deposit (W/D $$$): W 100
Input amount you would like to withdraw/deposit (W/D $$$): 



$ 100
