# Question 7 Level 2

Question:

Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡­Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 

Hints:

Note: In case of input data being supplied to the question, it should be assumed to be a console input in a comma-separated form.

In [19]:
# Import necessary libraries

import numpy as np

# Define variables

x = int(float(input("how many Rows?")))      # Rows
y = int(float(input("How many Columns?")))   # Columns
fill_value = int(input("Enter the fill value: ")) # a single integer to fill the array

# combine variables into an array

z = np.full((x,y),fill_value)

# Output

print(" ")
print(z)

how many Rows? 3
How many Columns? 3
Enter the fill value:  9


 
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [33]:
# Method 2
# Define variables

z = input("input rows & columns (',' seperated):")

# Create array

dimensions = [int(i) for i in z.split(',')]
x = dimensions[0]
y = dimensions[1]
array = [[0 for col in range(y)] for row in range(x)]

for row in range(x):
    for col in range(y):
        array[row][col] = row*col

# Output
        
print(array)

input rows & columns (',' seperated): 5,5


[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8], [0, 3, 6, 9, 12], [0, 4, 8, 12, 16]]
